apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ml-p2-de
  labels:
    app: api-ml-p2-de
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ml-p2-de
  template:
    metadata:
      labels:
        app: api-ml-p2-de
    spec:
      containers:
        - name: api-ml-container
          image: gcr.io/api-ml-project/api:GITHUB_SHA
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-ml-p2-de-service
  labels:
    app: api-ml-p2-de
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: api-ml-p2-de