apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      -image: gcr.io/$PROJECT_ID/$IMAGE:GITHUB_SHA
        name: api
        ports:
        -containerPort: 8000
          name: http

