FROM debian:latest

RUN apt-get update && apt-get install python3-pip -y && pip3 install flask==2.1.2


ADD server.py /fraudapi/main.py
ADD knn_fraud_model.sav /fraudapi/knn_fraud_model.sav

WORKDIR /fraudapi/

EXPOSE 8000

CMD uvicorn main:app 